#
# yEvo Pipeline Run Configuration
#

########################################################################
#
#  REQUIRED PARAMETERS
#
########################################################################


# absolute path to the cloned yevo_pipeline repo
REPO_DIR="/net/dunham/vol1/home/dennig2/yevo_pipeline"

# reference genome
REF_FASTA ="$REPO_DIR/data/genome/sacCer3.fasta"

# absolute path to fastq.gz location (e.g. <sample>_R1_001.fastq.gz files)
FASTQ_DIR="$REPO_DIR/pipelinetest/fastq"

# absolute path to desired pipeline output directory (will be created by snakemake)
OUTPUT_DIR="$REPO_DIR/pipelineoutput"
ANC_DIR="$REPO_DIR/pipelineanc"
#
# run pipeline
#

# construct pipeline file paths
LOG_FILE="$OUTPUT_DIR/00_logs/yevo_pipeline.log"
SNAKE_FILE="$REPO_DIR/workflow/Snakefile.py"
CONFIG_FILE="$REPO_DIR/config/config.yml"

# go to working directory
cd $REPO_DIR

