#
# yEvo Pipeline Run Configuration
#

########################################################################
#
#  REQUIRED PARAMETERS
#
########################################################################

# location of raw reads
fastq_dir: 'data/fastq/test'

# reference genome
ref_fasta: 'data/genome/sacCer3.fasta'



