---
anc_sampele: 
ref_fasta: '{{BASE_DIR}}/yevo_pipeline/data/genome/Geo_LMA_244.fasta'
output_dir: '{{BASE_DIR}}/yevo_pipeline/data/output'
fastq_dir: '{{BASE_DIR}}/yevo_pipeline/data/fastq'
annotate_sequences: '{{BASE_DIR}}/yevo_pipeline/data/annotate/orf_coding_all_R64-1-1_20110203.fasta'
annotate_noncoding: '{{BASE_DIR}}/yevo_pipeline/data/annotate/saccharomyces_cerevisiae_R64-1-1_20110208.gff.filtered'
annotate_genome: '{{BASE_DIR}}/yevo_pipeline/data/annotate/S288C_reference_sequence_R64-1-1_20110203.fsa'
